#!/bin/bash

#Source configuration file
source /etc/nfeed/nfeed.conf
echo Started nFeed cron on `date` >> $LOG
python $NFEEDDIR/nfeed-redis.py -u $URLLIST -t $SEARCHTERMLIST >> $LOG
echo Finished nFeed cron on `date` >> $LOG


