#!/bin/sh

#Source configuration file
source /etc/nfeed/nfeed.conf
echo connect to $HOSTNAME:$TORNADOSERVERPORT$TORNADOSERVERURL
python $NFEEDDIR/rss-tornado.py -p $TORNADOSERVERPORT -u $TORNADOSERVERURL
exit 0
