#!/bin/bash
#
#
# chkconfig: - 92 8
# 
#
#
#


# Source function library.
. /etc/init.d/functions

# Source configuration.
source /etc/nfeed/nfeed.conf

prog=nfeed-cron
lockfile=/var/lock/subsys/$prog

start() {


	# Start daemon.
	echo -n $"Starting $prog: "
	daemon $NFEEDDIR/nfeed-cron
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch $lockfile
	return $RETVAL
}

stop() {
	[ "$EUID" != "0" ] && exit 4
        echo -n $"Shutting down $prog: "
	killproc $prog
	RETVAL=$?
        echo
	[ $RETVAL -eq 0 ] && rm -f $lockfile
	return $RETVAL
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status $prog
	;;
  restart|force-reload)
	stop
	start
	;;
  try-restart|condrestart)
	if status $prog > /dev/null; then
	    stop
	    start
	fi
	;;
  reload)
	exit 3
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|try-restart|force-reload}"
	exit 2
esac
